SCHEMAS_DIR_PATH = "./schemas"
DATA_DIR_PATH = "./data"
OUTPUT_DIR_PATH = "./output"

CBOR_FILE_EXT = "cbor"
JADN_SCHEMA_FILE_EXT = "jadn"
JIDL_FILE_EXT = "jidl"
JSON_FILE_EXT = "json"
MARKDOWN_FILE_EXT = "md"
PLANT_UML_FILE_EXT = "puml"
XML_FILE_EXT = "xml"
XSD_FILE_EXT = "xsd"
UNKNOWN_EXT = "unknown"

VALID_DATA_FORMATS = [CBOR_FILE_EXT, JSON_FILE_EXT, XML_FILE_EXT]
# VALID_SCHEMA_FORMATS = [JADN_SCHEMA_FILE_EXT, JIDL_FILE_EXT, JSON_FILE_EXT, XSD_FILE_EXT]
VALID_SCHEMA_FORMATS = [JIDL_FILE_EXT, JSON_FILE_EXT, MARKDOWN_FILE_EXT, PLANT_UML_FILE_EXT, XSD_FILE_EXT]